### ISSUE TITLE
烧录Blaster固件后，Quartus认不出来，设别管理器能认出来

### ISSUE THREAD

**Issue by BigPig-Bro** [xjtuecho/CH552Nano#1]
现在的现象是：

1、上电WCH ISP软件能正常烧写CH552G芯片

2、烧写Blaster的HEX后，设备管理器能认出来，但是Quartus编程软件认不出来

3、烧写UART 的HEX，CH552G可作为串口正常工作

**Comment by xjtuecho** [comment]
试一下Quartus II 13.0 sp1，某个新版本QuartusII的USB-Blaster驱动有问题

**Comment by BigPig-Bro** [comment]
好的，我这边试过了，卸载掉原本的驱动，再安装13.1 的 usb blaster驱动，就可以识别和下载了（速度和反应确实慢点，问题不大），不过希望您能够在主页注明，不要使用新版Quartus进行驱动安装，（我装的18 20 21 都寄了），谢谢

**Comment by xjtuecho** [comment]
> 好的，我这边试过了，卸载掉原本的驱动，再安装13.1 的 usb blaster驱动，就可以识别和下载了（速度和反应确实慢点，问题不大），不过希望您能够在主页注明，不要使用新版Quartus进行驱动安装，（我装的18 20 21 都寄了），谢谢

仓库中已经添加13.0sp1版本驱动，并且在README中增加了说明。
CH552性能就这样了，如果经常使用，并且对速度有一定要求可以采购CH546或者CH571版本的USB-Blaster，速度快很多。
